import { Page, expect, Locator } from '@playwright/test';

export class NominationsPage {
  // Selectors
    private menuTab: Locator;
      private nominationsTab: Locator;
        private votingTab: Locator;
          private finalEvalTab: Locator;
            private pageTitle: Locator;
              private infoText: Locator;
                private addNomineeBtn: Locator;
                  private submitBtn: Locator;
                    private popup: Locator;
                      private nameField: Locator;
                        private noteField: Locator;
                          private addBtnInPopup: Locator;
                            private cancelBtnInPopup: Locator;
                              private requiredError: Locator;
                                private successMessage: Locator;
                                  private yearFilter: Locator;

                                    constructor(private page: Page) {
                                        this.menuTab = page.locator('a, button, li').filter({ hasText: /Jury Voting System|نظام تصويت لجنة التحكيم/ }).first();
                                            this.nominationsTab = page.locator('[role="tab"], button, a').filter({ hasText: /^Nominations$|^الترشيحات$/ }).first();
                                                this.votingTab = page.locator('[role="tab"], button, a').filter({ hasText: /^Voting$|^التصويت$/ }).first();
                                                    this.finalEvalTab = page.locator('[role="tab"], button, a').filter({ hasText: /Final Evaluation|التقييم النهائي/ }).first();
                                                        this.pageTitle = page.locator('h1, h2, h3').filter({ hasText: /Submitting Nominees|تقديم المرشحين|Submitted Nominees|المرشحين المقدمين/ }).first();
                                                            this.infoText = page.locator('p, span, div').filter({ hasText: /Add as many nominations|يمكنك إضافة|This page displays a list|تعرض هذه الصفحة/ }).first();
                                                                this.addNomineeBtn = page.locator('button').filter({ hasText: /Add Nominee|إضافة مرشح جديد/ }).first();
                                                                    this.submitBtn = page.locator('button[type="submit"], button').filter({ hasText: /^Submit$|^إرسال$/ }).first();
                                                                        this.popup = page.locator('[role="dialog"], .modal, .popup').first();
                                                                            this.nameField = page.locator('input[name="name"], input[placeholder*="Name"], input[placeholder*="الاسم"]').first();
                                                                                this.noteField = page.locator('textarea[name="note"], input[name="note"], textarea[placeholder*="notes"], textarea[placeholder*="ملاحظات"]').first();
                                                                                    this.addBtnInPopup = page.locator('[role="dialog"] button, .modal button, .popup button').filter({ hasText: /^Add$|^إضافة$/ }).first();
                                                                                        this.cancelBtnInPopup = page.locator('[role="dialog"] button, .modal button, .popup button').filter({ hasText: /^Cancel$|^إلغاء$/ }).first();
                                                                                            this.requiredError = page.locator('.error, [role="alert"], .field-error').filter({ hasText: /This field is required|هذا الحقل مطلوب/ }).first();
                                                                                                this.successMessage = page.locator('.success, [role="status"], .toast, .notification').filter({ hasText: /Submitted Successfully|تم النشر بنجاح/ }).first();
                                                                                                    this.yearFilter = page.locator('select, [role="combobox"]').filter({ hasText: /2026|year|سنة/ }).first();
                                                                                                      }
                                                                                                      
                                                                                                        // Navigation
                                                                                                          async navigateToJuryVotingSystem() {
                                                                                                              await this.menuTab.click();
                                                                                                                  await this.page.waitForLoadState('networkidle');
                                                                                                                    }
                                                                                                                    
                                                                                                                      async clickNominationsTab() {
                                                                                                                          await this.nominationsTab.click();
                                                                                                                              await this.page.waitForLoadState('networkidle');
                                                                                                                                }
                                                                                                                                
                                                                                                                                  async clickVotingTab() {
                                                                                                                                      await this.votingTab.click();
                                                                                                                                          await this.page.waitForLoadState('networkidle');
                                                                                                                                            }
                                                                                                                                            
                                                                                                                                              async clickFinalEvaluationTab() {
                                                                                                                                                  await this.finalEvalTab.click();
                                                                                                                                                      await this.page.waitForLoadState('networkidle');
                                                                                                                                                        }
                                                                                                                                                        
                                                                                                                                                          // Assertions — Navigation
                                                                                                                                                            async verifyMenuTabVisible(lang: 'en' | 'ar') {
                                                                                                                                                                const label = lang === 'en' ? 'Jury Voting System' : 'نظام تصويت لجنة التحكيم';
                                                                                                                                                                    await expect(this.page.locator('a, button, li').filter({ hasText: label }).first()).toBeVisible();
                                                                                                                                                                      }
                                                                                                                                                                      
                                                                                                                                                                        async verifyMenuTabNotVisible() {
                                                                                                                                                                            await expect(this.menuTab).not.toBeVisible();
                                                                                                                                                                              }
                                                                                                                                                                              
                                                                                                                                                                                async verifyYearFilterDefaultCurrentYear() {
                                                                                                                                                                                    const currentYear = new Date().getFullYear().toString();
                                                                                                                                                                                        await expect(this.yearFilter).toContainText(currentYear);
                                                                                                                                                                                          }
                                                                                                                                                                                          
                                                                                                                                                                                            async verifyThreeTabs(lang: 'en' | 'ar') {
                                                                                                                                                                                                if (lang === 'en') {
                                                                                                                                                                                                      await expect(this.page.locator('[role="tab"], button, a').filter({ hasText: 'Nominations' }).first()).toBeVisible();
                                                                                                                                                                                                            await expect(this.page.locator('[role="tab"], button, a').filter({ hasText: 'Voting' }).first()).toBeVisible();
                                                                                                                                                                                                                  await expect(this.page.locator('[role="tab"], button, a').filter({ hasText: 'Final Evaluation' }).first()).toBeVisible();
                                                                                                                                                                                                                      } else {
                                                                                                                                                                                                                            await expect(this.page.locator('[role="tab"], button, a').filter({ hasText: 'الترشيحات' }).first()).toBeVisible();
                                                                                                                                                                                                                                  await expect(this.page.locator('[role="tab"], button, a').filter({ hasText: 'التصويت' }).first()).toBeVisible();
                                                                                                                                                                                                                                        await expect(this.page.locator('[role="tab"], button, a').filter({ hasText: 'التقييم النهائي' }).first()).toBeVisible();
                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                async verifyNominationsTabActiveByDefault() {
                                                                                                                                                                                                                                                    await expect(this.nominationsTab).toHaveAttribute('aria-selected', 'true');
                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                        // Assertions — Page content
                                                                                                                                                                                                                                                          async verifyPageTitle(expectedTitle: string) {
                                                                                                                                                                                                                                                              await expect(this.page.locator('h1, h2, h3').filter({ hasText: expectedTitle }).first()).toBeVisible();
                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                  async verifyInfoText(expectedText: string) {
                                                                                                                                                                                                                                                                      await expect(this.page.locator('body')).toContainText(expectedText);
                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                          async verifyTableColumns(columns: string[]) {
                                                                                                                                                                                                                                                                              for (const col of columns) {
                                                                                                                                                                                                                                                                                    await expect(this.page.locator('th, [role="columnheader"]').filter({ hasText: col }).first()).toBeVisible();
                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                            async verifyTextDirection(expectedDir: 'ltr' | 'rtl') {
                                                                                                                                                                                                                                                                                                const dir = await this.page.locator('html').getAttribute('dir');
                                                                                                                                                                                                                                                                                                    const bodyDir = await this.page.locator('body').getAttribute('dir');
                                                                                                                                                                                                                                                                                                        const actualDir = dir || bodyDir || 'ltr';
                                                                                                                                                                                                                                                                                                            expect(actualDir.toLowerCase()).toBe(expectedDir);
                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                // Add Nominee actions
                                                                                                                                                                                                                                                                                                                  async clickAddNominee() {
                                                                                                                                                                                                                                                                                                                      await this.addNomineeBtn.click();
                                                                                                                                                                                                                                                                                                                          await expect(this.popup.or(this.page.locator('[role="dialog"]').first())).toBeVisible();
                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                              async fillNomineeName(name: string) {
                                                                                                                                                                                                                                                                                                                                  await this.nameField.fill(name);
                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                      async fillNomineeNote(note: string) {
                                                                                                                                                                                                                                                                                                                                          await this.noteField.fill(note);
                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                              async clickAddInPopup() {
                                                                                                                                                                                                                                                                                                                                                  await this.addBtnInPopup.click();
                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                      async clickCancelInPopup() {
                                                                                                                                                                                                                                                                                                                                                          await this.cancelBtnInPopup.click();
                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                              async verifyPopupClosed() {
                                                                                                                                                                                                                                                                                                                                                                  await expect(this.popup).not.toBeVisible();
                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                      async verifyRequiredError(expectedText: string) {
                                                                                                                                                                                                                                                                                                                                                                          await expect(this.page.locator('body')).toContainText(expectedText);
                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                              async verifyNomineeInList(nomineeName: string) {
                                                                                                                                                                                                                                                                                                                                                                                  await expect(this.page.locator('table, [role="table"], .list').filter({ hasText: nomineeName }).first()).toBeVisible();
                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                      async verifyNomineeNotInList(nomineeName: string) {
                                                                                                                                                                                                                                                                                                                                                                                          await expect(this.page.locator('table, [role="table"], .list').filter({ hasText: nomineeName }).first()).not.toBeVisible();
                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                              async verifyAddButtonEnabled() {
                                                                                                                                                                                                                                                                                                                                                                                                  await expect(this.addBtnInPopup).toBeEnabled();
                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                      async verifyAddNomineeBtnDisabled() {
                                                                                                                                                                                                                                                                                                                                                                                                          await expect(this.addNomineeBtn).toBeDisabled();
                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                              // Delete actions
                                                                                                                                                                                                                                                                                                                                                                                                                async clickDeleteOnNominee(nomineeName: string) {
                                                                                                                                                                                                                                                                                                                                                                                                                    const row = this.page.locator('tr, [role="row"]').filter({ hasText: nomineeName }).first();
                                                                                                                                                                                                                                                                                                                                                                                                                        await row.locator('button').filter({ hasText: /delete|حذف/i }).click();
                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                            async verifyDeleteConfirmPopup(lang: 'en' | 'ar') {
                                                                                                                                                                                                                                                                                                                                                                                                                                const msg = lang === 'en' ? 'Are you sure you want to delete?' : 'هل أنت متأكد من الحذف؟';
                                                                                                                                                                                                                                                                                                                                                                                                                                    await expect(this.page.locator('body')).toContainText(msg);
                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                        async clickYesOnConfirm() {
                                                                                                                                                                                                                                                                                                                                                                                                                                            await this.page.locator('button').filter({ hasText: /^Yes$|^نعم$/ }).first().click();
                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                async clickCancelOnConfirm() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                    await this.page.locator('button').filter({ hasText: /^Cancel$|^إلغاء$/ }).first().click();
                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Edit actions
                                                                                                                                                                                                                                                                                                                                                                                                                                                          async clickEditOnNominee(nomineeName: string) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                              const row = this.page.locator('tr, [role="row"]').filter({ hasText: nomineeName }).first();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  await row.locator('button').filter({ hasText: /edit|تعديل/i }).click();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      async verifyEditPopupTitle(lang: 'en' | 'ar') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const title = lang === 'en' ? 'Edit Suggestion' : 'تعديل مرشح';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              await expect(this.page.locator('body')).toContainText(title);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // Submit actions
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    async verifySubmitBtnDisabled() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        await expect(this.submitBtn).toBeDisabled();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            async verifySubmitBtnEnabled() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await expect(this.submitBtn).toBeEnabled();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    async clickSubmit() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        await this.submitBtn.click();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            async verifySuccessMessage(lang: 'en' | 'ar') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const msg = lang === 'en' ? 'Submitted Successfully' : 'تم النشر بنجاح';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await expect(this.page.locator('body')).toContainText(msg);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        async verifyNotePlaceholder(lang: 'en' | 'ar') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const placeholder = lang === 'en' ? 'Add notes or related links' : 'أضف ملاحظات أو روابط ذات صلة';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await expect(this.noteField).toHaveAttribute('placeholder', placeholder);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
