/**
 * Admin Nominations Tab Tests
  * Story: SP-1796
   * Pre-condition: System in State 1 (Nominations submitted by judges)
    * Tags: @smoke @regression @SP-1796 @lang-en @lang-ar @negative @edge
     */

     import { test, expect } from '@playwright/test';
     import { LoginPage } from '../../pages/LoginPage';
     import { NominationsPage } from '../../pages/NominationsPage';
     import { USERS, TEXT_EN, TEXT_AR } from '../../fixtures/testData';

     test.describe('Admin Nominations Tab @regression @SP-1796', () => {

       test.beforeEach(async ({ page }) => {
           const loginPage = new LoginPage(page);
               await loginPage.login(USERS.admin.email, USERS.admin.password);
                 });

                   test('@smoke @lang-en - Admin title and info text display correctly in English', async ({ page }) => {
                       const nominationsPage = new NominationsPage(page);
                           const loginPage = new LoginPage(page);
                               await loginPage.setLanguage('en');
                                   await nominationsPage.navigateToJuryVotingSystem();
                                       await nominationsPage.clickNominationsTab();
                                           await nominationsPage.verifyPageTitle(TEXT_EN.adminNominations.title);
                                               await nominationsPage.verifyInfoText(TEXT_EN.adminNominations.infoText);
                                                   await nominationsPage.verifyTextDirection('ltr');
                                                     });

                                                       test('@smoke @lang-ar - Admin title and info text display correctly in Arabic', async ({ page }) => {
                                                           const nominationsPage = new NominationsPage(page);
                                                               const loginPage = new LoginPage(page);
                                                                   await loginPage.setLanguage('ar');
                                                                       await nominationsPage.navigateToJuryVotingSystem();
                                                                           await nominationsPage.clickNominationsTab();
                                                                               await nominationsPage.verifyPageTitle(TEXT_AR.adminNominations.title);
                                                                                   await nominationsPage.verifyInfoText(TEXT_AR.adminNominations.infoText);
                                                                                       await nominationsPage.verifyTextDirection('rtl');
                                                                                         });

                                                                                           test('@smoke @lang-en - Admin table columns display correctly in English', async ({ page }) => {
                                                                                               const nominationsPage = new NominationsPage(page);
                                                                                                   const loginPage = new LoginPage(page);
                                                                                                       await loginPage.setLanguage('en');
                                                                                                           await nominationsPage.navigateToJuryVotingSystem();
                                                                                                               await nominationsPage.clickNominationsTab();
                                                                                                                   await nominationsPage.verifyTableColumns(TEXT_EN.adminNominations.tableColumns);
                                                                                                                       await nominationsPage.verifyTextDirection('ltr');
                                                                                                                         });
                                                                                                                         
                                                                                                                           test('@smoke @lang-ar - Admin table columns display correctly in Arabic', async ({ page }) => {
                                                                                                                               const nominationsPage = new NominationsPage(page);
                                                                                                                                   const loginPage = new LoginPage(page);
                                                                                                                                       await loginPage.setLanguage('ar');
                                                                                                                                           await nominationsPage.navigateToJuryVotingSystem();
                                                                                                                                               await nominationsPage.clickNominationsTab();
                                                                                                                                                   await nominationsPage.verifyTableColumns(TEXT_AR.adminNominations.tableColumns);
                                                                                                                                                       await nominationsPage.verifyTextDirection('rtl');
                                                                                                                                                         });
                                                                                                                                                         
                                                                                                                                                           test('@regression @lang-en - Search filter placeholder shows correctly in English', async ({ page }) => {
                                                                                                                                                               const nominationsPage = new NominationsPage(page);
                                                                                                                                                                   const loginPage = new LoginPage(page);
                                                                                                                                                                       await loginPage.setLanguage('en');
                                                                                                                                                                           await nominationsPage.navigateToJuryVotingSystem();
                                                                                                                                                                               await nominationsPage.clickNominationsTab();
                                                                                                                                                                                   const searchField = page.locator('input[placeholder*="Search Nominee"]');
                                                                                                                                                                                       await expect(searchField).toHaveAttribute('placeholder', TEXT_EN.adminNominations.searchPlaceholder);
                                                                                                                                                                                           await nominationsPage.verifyTextDirection('ltr');
                                                                                                                                                                                             });
                                                                                                                                                                                             
                                                                                                                                                                                               test('@regression @lang-ar - Search filter placeholder shows correctly in Arabic', async ({ page }) => {
                                                                                                                                                                                                   const nominationsPage = new NominationsPage(page);
                                                                                                                                                                                                       const loginPage = new LoginPage(page);
                                                                                                                                                                                                           await loginPage.setLanguage('ar');
                                                                                                                                                                                                               await nominationsPage.navigateToJuryVotingSystem();
                                                                                                                                                                                                                   await nominationsPage.clickNominationsTab();
                                                                                                                                                                                                                       const searchField = page.locator(`input[placeholder*="${TEXT_AR.adminNominations.searchPlaceholder}"]`);
                                                                                                                                                                                                                           await expect(searchField).toBeVisible();
                                                                                                                                                                                                                               await nominationsPage.verifyTextDirection('rtl');
                                                                                                                                                                                                                                 });
                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                   test('@negative @lang-en - Required error shows in English when add popup Name is empty', async ({ page }) => {
                                                                                                                                                                                                                                       const nominationsPage = new NominationsPage(page);
                                                                                                                                                                                                                                           const loginPage = new LoginPage(page);
                                                                                                                                                                                                                                               await loginPage.setLanguage('en');
                                                                                                                                                                                                                                                   await nominationsPage.navigateToJuryVotingSystem();
                                                                                                                                                                                                                                                       await nominationsPage.clickNominationsTab();
                                                                                                                                                                                                                                                           await nominationsPage.clickAddNominee();
                                                                                                                                                                                                                                                               await nominationsPage.clickAddInPopup();
                                                                                                                                                                                                                                                                   await nominationsPage.verifyRequiredError(TEXT_EN.adminNominations.requiredError);
                                                                                                                                                                                                                                                                       await nominationsPage.verifyTextDirection('ltr');
                                                                                                                                                                                                                                                                         });
                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                           test('@negative @lang-ar - Required error shows in Arabic when add popup Name is empty', async ({ page }) => {
                                                                                                                                                                                                                                                                               const nominationsPage = new NominationsPage(page);
                                                                                                                                                                                                                                                                                   const loginPage = new LoginPage(page);
                                                                                                                                                                                                                                                                                       await loginPage.setLanguage('ar');
                                                                                                                                                                                                                                                                                           await nominationsPage.navigateToJuryVotingSystem();
                                                                                                                                                                                                                                                                                               await nominationsPage.clickNominationsTab();
                                                                                                                                                                                                                                                                                                   await nominationsPage.clickAddNominee();
                                                                                                                                                                                                                                                                                                       await nominationsPage.clickAddInPopup();
                                                                                                                                                                                                                                                                                                           await nominationsPage.verifyRequiredError(TEXT_AR.adminNominations.requiredError);
                                                                                                                                                                                                                                                                                                               await nominationsPage.verifyTextDirection('rtl');
                                                                                                                                                                                                                                                                                                                 });
                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                   test('@regression @lang-en - Delete confirmation popup shows correctly in English', async ({ page }) => {
                                                                                                                                                                                                                                                                                                                       const nominationsPage = new NominationsPage(page);
                                                                                                                                                                                                                                                                                                                           const loginPage = new LoginPage(page);
                                                                                                                                                                                                                                                                                                                               await loginPage.setLanguage('en');
                                                                                                                                                                                                                                                                                                                                   await nominationsPage.navigateToJuryVotingSystem();
                                                                                                                                                                                                                                                                                                                                       await nominationsPage.clickNominationsTab();
                                                                                                                                                                                                                                                                                                                                           const firstNominee = await page.locator('tr, [role="row"]').nth(1).textContent();
                                                                                                                                                                                                                                                                                                                                               if (firstNominee) {
                                                                                                                                                                                                                                                                                                                                                     await nominationsPage.clickDeleteOnNominee(firstNominee.trim());
                                                                                                                                                                                                                                                                                                                                                           await expect(page.locator('body')).toContainText("Are you sure you want to delete");
                                                                                                                                                                                                                                                                                                                                                                 await nominationsPage.verifyTextDirection('ltr');
                                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                                       });
                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                         test('@regression @lang-ar - Delete confirmation popup shows correctly in Arabic', async ({ page }) => {
                                                                                                                                                                                                                                                                                                                                                                             const nominationsPage = new NominationsPage(page);
                                                                                                                                                                                                                                                                                                                                                                                 const loginPage = new LoginPage(page);
                                                                                                                                                                                                                                                                                                                                                                                     await loginPage.setLanguage('ar');
                                                                                                                                                                                                                                                                                                                                                                                         await nominationsPage.navigateToJuryVotingSystem();
                                                                                                                                                                                                                                                                                                                                                                                             await nominationsPage.clickNominationsTab();
                                                                                                                                                                                                                                                                                                                                                                                                 const firstNominee = await page.locator('tr, [role="row"]').nth(1).textContent();
                                                                                                                                                                                                                                                                                                                                                                                                     if (firstNominee) {
                                                                                                                                                                                                                                                                                                                                                                                                           await nominationsPage.clickDeleteOnNominee(firstNominee.trim());
                                                                                                                                                                                                                                                                                                                                                                                                                 await expect(page.locator('body')).toContainText('هل أنت متأكد من حذف');
                                                                                                                                                                                                                                                                                                                                                                                                                       await nominationsPage.verifyTextDirection('rtl');
                                                                                                                                                                                                                                                                                                                                                                                                                           }
                                                                                                                                                                                                                                                                                                                                                                                                                             });
                                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                               test('@edge - Submit button disabled when fewer than 3 nominees selected per award', async ({ page }) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                   const nominationsPage = new NominationsPage(page);
                                                                                                                                                                                                                                                                                                                                                                                                                                       await nominationsPage.navigateToJuryVotingSystem();
                                                                                                                                                                                                                                                                                                                                                                                                                                           await nominationsPage.clickNominationsTab();
                                                                                                                                                                                                                                                                                                                                                                                                                                               // Without selecting 3 per award, submit should be disabled
                                                                                                                                                                                                                                                                                                                                                                                                                                                   await nominationsPage.verifySubmitBtnDisabled();
                                                                                                                                                                                                                                                                                                                                                                                                                                                     });
                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                       test('@smoke @lang-en - Submit confirmation popup displays correctly in English', async ({ page }) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                           const nominationsPage = new NominationsPage(page);
                                                                                                                                                                                                                                                                                                                                                                                                                                                               const loginPage = new LoginPage(page);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                   await loginPage.setLanguage('en');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       await nominationsPage.navigateToJuryVotingSystem();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                           await nominationsPage.clickNominationsTab();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                               // NOTE: Select at least 3 per award before this test
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   await nominationsPage.verifySubmitBtnEnabled();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       await nominationsPage.clickSubmit();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           await expect(page.locator('body')).toContainText(TEXT_EN.adminNominations.submitConfirm);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               await nominationsPage.verifyTextDirection('ltr');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   test('@smoke @lang-ar - Submit confirmation popup displays correctly in Arabic', async ({ page }) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       const nominationsPage = new NominationsPage(page);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           const loginPage = new LoginPage(page);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               await loginPage.setLanguage('ar');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   await nominationsPage.navigateToJuryVotingSystem();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       await nominationsPage.clickNominationsTab();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           await nominationsPage.verifySubmitBtnEnabled();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               await nominationsPage.clickSubmit();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   await expect(page.locator('body')).toContainText(TEXT_AR.adminNominations.submitConfirm);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       await nominationsPage.verifyTextDirection('rtl');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           test('@smoke @SP-1796 @SP-1794 - After confirm submit button is hidden and list is read-only', async ({ page }) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               const nominationsPage = new NominationsPage(page);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   await nominationsPage.navigateToJuryVotingSystem();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       await nominationsPage.clickNominationsTab();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           await nominationsPage.clickSubmit();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               await nominationsPage.clickYesOnConfirm();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   await nominationsPage.verifySubmitBtnDisabled();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       // Verify edit/delete not available
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           const editBtn = page.locator('button').filter({ hasText: /edit|تعديل/i }).first();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               await expect(editBtn).not.toBeVisible();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 });
