/**
 * Voting Tab Tests - Judge Side (SP-1794) & Admin Side (SP-1797)
  * Pre-conditions:
   *   - State 1: For pending text tests (nominations not yet published)
    *   - State 2: For voting flow tests (admin has published refined list)
     *   - State 3: For admin top-3 selection (all judges have voted)
      */

      import { test, expect } from '@playwright/test';
      import { LoginPage } from '../../pages/LoginPage';
      import { NominationsPage } from '../../pages/NominationsPage';
      import { VotingPage } from '../../pages/VotingPage';
      import { USERS, TEXT_EN, TEXT_AR } from '../../fixtures/testData';

      // ===== JUDGE VOTING TESTS (SP-1794) =====
      test.describe('Judge Voting Tab @regression @SP-1794', () => {

        test.beforeEach(async ({ page }) => {
            const loginPage = new LoginPage(page);
                await loginPage.login(USERS.judge1.email, USERS.judge1.password);
                  });

                    test('@smoke @lang-en @SP-1794 - Voting tab shows pending text in English (State 1)', async ({ page }) => {
                        const loginPage = new LoginPage(page);
                            const nominationsPage = new NominationsPage(page);
                                const votingPage = new VotingPage(page);
                                    await loginPage.setLanguage('en');
                                        await nominationsPage.navigateToJuryVotingSystem();
                                            await nominationsPage.clickVotingTab();
                                                await votingPage.verifyPendingText('en');
                                                    await votingPage.verifyTextDirection('ltr');
                                                      });

                                                        test('@smoke @lang-ar @SP-1794 - Voting tab shows pending text in Arabic (State 1)', async ({ page }) => {
                                                            const loginPage = new LoginPage(page);
                                                                const nominationsPage = new NominationsPage(page);
                                                                    const votingPage = new VotingPage(page);
                                                                        await loginPage.setLanguage('ar');
                                                                            await nominationsPage.navigateToJuryVotingSystem();
                                                                                await nominationsPage.clickVotingTab();
                                                                                    await votingPage.verifyPendingText('ar');
                                                                                        await votingPage.verifyTextDirection('rtl');
                                                                                          });

                                                                                            test('@smoke @lang-en @SP-1794 - Voting instruction text shows in English (State 2)', async ({ page }) => {
                                                                                                const loginPage = new LoginPage(page);
                                                                                                    const nominationsPage = new NominationsPage(page);
                                                                                                        const votingPage = new VotingPage(page);
                                                                                                            await loginPage.setLanguage('en');
                                                                                                                await nominationsPage.navigateToJuryVotingSystem();
                                                                                                                    await nominationsPage.clickVotingTab();
                                                                                                                        await votingPage.verifyInstructionText('en');
                                                                                                                            await votingPage.verifyTextDirection('ltr');
                                                                                                                              });
                                                                                                                              
                                                                                                                                test('@smoke @lang-ar @SP-1794 - Voting instruction text shows in Arabic (State 2)', async ({ page }) => {
                                                                                                                                    const loginPage = new LoginPage(page);
                                                                                                                                        const nominationsPage = new NominationsPage(page);
                                                                                                                                            const votingPage = new VotingPage(page);
                                                                                                                                                await loginPage.setLanguage('ar');
                                                                                                                                                    await nominationsPage.navigateToJuryVotingSystem();
                                                                                                                                                        await nominationsPage.clickVotingTab();
                                                                                                                                                            await votingPage.verifyInstructionText('ar');
                                                                                                                                                                await votingPage.verifyTextDirection('rtl');
                                                                                                                                                                  });
                                                                                                                                                                  
                                                                                                                                                                    test('@negative @SP-1794 - Submit disabled when fewer than 3 nominees selected per award', async ({ page }) => {
                                                                                                                                                                        const nominationsPage = new NominationsPage(page);
                                                                                                                                                                            const votingPage = new VotingPage(page);
                                                                                                                                                                                await nominationsPage.navigateToJuryVotingSystem();
                                                                                                                                                                                    await nominationsPage.clickVotingTab();
                                                                                                                                                                                        await votingPage.verifySubmitBtnDisabled();
                                                                                                                                                                                          });
                                                                                                                                                                                          
                                                                                                                                                                                            test('@regression @lang-en @SP-1794 - Vote submit confirmation popup shows in English', async ({ page }) => {
                                                                                                                                                                                                const loginPage = new LoginPage(page);
                                                                                                                                                                                                    const nominationsPage = new NominationsPage(page);
                                                                                                                                                                                                        const votingPage = new VotingPage(page);
                                                                                                                                                                                                            await loginPage.setLanguage('en');
                                                                                                                                                                                                                await nominationsPage.navigateToJuryVotingSystem();
                                                                                                                                                                                                                    await nominationsPage.clickVotingTab();
                                                                                                                                                                                                                        // NOTE: Select 3 nominees per award first (depends on State 2 setup)
                                                                                                                                                                                                                            await votingPage.verifySubmitBtnEnabled();
                                                                                                                                                                                                                                await votingPage.clickSubmit();
                                                                                                                                                                                                                                    await votingPage.verifySubmitConfirmPopup('en');
                                                                                                                                                                                                                                        await votingPage.verifyTextDirection('ltr');
                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                            test('@regression @lang-ar @SP-1794 - Vote submit confirmation popup shows in Arabic', async ({ page }) => {
                                                                                                                                                                                                                                                const loginPage = new LoginPage(page);
                                                                                                                                                                                                                                                    const nominationsPage = new NominationsPage(page);
                                                                                                                                                                                                                                                        const votingPage = new VotingPage(page);
                                                                                                                                                                                                                                                            await loginPage.setLanguage('ar');
                                                                                                                                                                                                                                                                await nominationsPage.navigateToJuryVotingSystem();
                                                                                                                                                                                                                                                                    await nominationsPage.clickVotingTab();
                                                                                                                                                                                                                                                                        await votingPage.verifySubmitBtnEnabled();
                                                                                                                                                                                                                                                                            await votingPage.clickSubmit();
                                                                                                                                                                                                                                                                                await votingPage.verifySubmitConfirmPopup('ar');
                                                                                                                                                                                                                                                                                    await votingPage.verifyTextDirection('rtl');
                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                        test('@smoke @SP-1794 @SP-1797 - Confirm vote submission makes view read-only', async ({ page }) => {
                                                                                                                                                                                                                                                                                            const nominationsPage = new NominationsPage(page);
                                                                                                                                                                                                                                                                                                const votingPage = new VotingPage(page);
                                                                                                                                                                                                                                                                                                    await nominationsPage.navigateToJuryVotingSystem();
                                                                                                                                                                                                                                                                                                        await nominationsPage.clickVotingTab();
                                                                                                                                                                                                                                                                                                            await votingPage.clickSubmit();
                                                                                                                                                                                                                                                                                                                await votingPage.confirmSubmit();
                                                                                                                                                                                                                                                                                                                    await votingPage.verifyVotingReadOnly();
                                                                                                                                                                                                                                                                                                                        await votingPage.verifySubmitBtnHidden();
                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                            test('@regression @SP-1794 - Cancel on vote confirmation keeps voting editable', async ({ page }) => {
                                                                                                                                                                                                                                                                                                                                const nominationsPage = new NominationsPage(page);
                                                                                                                                                                                                                                                                                                                                    const votingPage = new VotingPage(page);
                                                                                                                                                                                                                                                                                                                                        await nominationsPage.navigateToJuryVotingSystem();
                                                                                                                                                                                                                                                                                                                                            await nominationsPage.clickVotingTab();
                                                                                                                                                                                                                                                                                                                                                await votingPage.clickSubmit();
                                                                                                                                                                                                                                                                                                                                                    await votingPage.cancelSubmit();
                                                                                                                                                                                                                                                                                                                                                        await votingPage.verifySubmitBtnEnabled();
                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                          // ===== ADMIN VOTING TESTS (SP-1797) =====
                                                                                                                                                                                                                                                                                                                                                          test.describe('Admin Voting Tab @regression @SP-1797', () => {
                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                            test.beforeEach(async ({ page }) => {
                                                                                                                                                                                                                                                                                                                                                                const loginPage = new LoginPage(page);
                                                                                                                                                                                                                                                                                                                                                                    await loginPage.login(USERS.admin.email, USERS.admin.password);
                                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                        test('@smoke @lang-en @SP-1797 - Admin voting tab shows pending text in English (State 1)', async ({ page }) => {
                                                                                                                                                                                                                                                                                                                                                                            const loginPage = new LoginPage(page);
                                                                                                                                                                                                                                                                                                                                                                                const nominationsPage = new NominationsPage(page);
                                                                                                                                                                                                                                                                                                                                                                                    const votingPage = new VotingPage(page);
                                                                                                                                                                                                                                                                                                                                                                                        await loginPage.setLanguage('en');
                                                                                                                                                                                                                                                                                                                                                                                            await nominationsPage.navigateToJuryVotingSystem();
                                                                                                                                                                                                                                                                                                                                                                                                await nominationsPage.clickVotingTab();
                                                                                                                                                                                                                                                                                                                                                                                                    await votingPage.verifyAdminPendingText('en');
                                                                                                                                                                                                                                                                                                                                                                                                        await votingPage.verifyTextDirection('ltr');
                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                            test('@smoke @lang-ar @SP-1797 - Admin voting tab shows pending text in Arabic (State 1)', async ({ page }) => {
                                                                                                                                                                                                                                                                                                                                                                                                                const loginPage = new LoginPage(page);
                                                                                                                                                                                                                                                                                                                                                                                                                    const nominationsPage = new NominationsPage(page);
                                                                                                                                                                                                                                                                                                                                                                                                                        const votingPage = new VotingPage(page);
                                                                                                                                                                                                                                                                                                                                                                                                                            await loginPage.setLanguage('ar');
                                                                                                                                                                                                                                                                                                                                                                                                                                await nominationsPage.navigateToJuryVotingSystem();
                                                                                                                                                                                                                                                                                                                                                                                                                                    await nominationsPage.clickVotingTab();
                                                                                                                                                                                                                                                                                                                                                                                                                                        await votingPage.verifyAdminPendingText('ar');
                                                                                                                                                                                                                                                                                                                                                                                                                                            await votingPage.verifyTextDirection('rtl');
                                                                                                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                test('@smoke @lang-en @SP-1797 - Admin voting instruction text shows in English (State 3)', async ({ page }) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                    const loginPage = new LoginPage(page);
                                                                                                                                                                                                                                                                                                                                                                                                                                                        const nominationsPage = new NominationsPage(page);
                                                                                                                                                                                                                                                                                                                                                                                                                                                            const votingPage = new VotingPage(page);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                await loginPage.setLanguage('en');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await nominationsPage.navigateToJuryVotingSystem();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        await nominationsPage.clickVotingTab();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await votingPage.verifyAdminInstructionText('en');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await votingPage.verifyTextDirection('ltr');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    test('@smoke @lang-ar @SP-1797 - Admin voting instruction text shows in Arabic (State 3)', async ({ page }) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const loginPage = new LoginPage(page);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const nominationsPage = new NominationsPage(page);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const votingPage = new VotingPage(page);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await loginPage.setLanguage('ar');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        await nominationsPage.navigateToJuryVotingSystem();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await nominationsPage.clickVotingTab();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await votingPage.verifyAdminInstructionText('ar');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await votingPage.verifyTextDirection('rtl');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        test('@edge @SP-1797 - Admin submit disabled when fewer than 3 per award selected', async ({ page }) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const nominationsPage = new NominationsPage(page);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const votingPage = new VotingPage(page);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await nominationsPage.navigateToJuryVotingSystem();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        await nominationsPage.clickVotingTab();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await votingPage.verifySubmitBtnDisabled();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                test('@smoke @lang-en @SP-1797 - Admin submit confirmation popup shows in English', async ({ page }) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const loginPage = new LoginPage(page);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const nominationsPage = new NominationsPage(page);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const votingPage = new VotingPage(page);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await loginPage.setLanguage('en');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await nominationsPage.navigateToJuryVotingSystem();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        await nominationsPage.clickVotingTab();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await votingPage.verifySubmitBtnEnabled();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await votingPage.clickSubmit();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await votingPage.verifyAdminSubmitConfirmPopup('en');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        await votingPage.verifyTextDirection('ltr');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            test('@smoke @lang-ar @SP-1797 - Admin submit confirmation popup shows in Arabic', async ({ page }) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const loginPage = new LoginPage(page);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const nominationsPage = new NominationsPage(page);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const votingPage = new VotingPage(page);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await loginPage.setLanguage('ar');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await nominationsPage.navigateToJuryVotingSystem();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await nominationsPage.clickVotingTab();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        await votingPage.verifySubmitBtnEnabled();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await votingPage.clickSubmit();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await votingPage.verifyAdminSubmitConfirmPopup('ar');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await votingPage.verifyTextDirection('rtl');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        test('@smoke @SP-1797 @SP-1795 - After admin confirms top-3, submit hidden and list read-only', async ({ page }) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const nominationsPage = new NominationsPage(page);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const votingPage = new VotingPage(page);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await nominationsPage.navigateToJuryVotingSystem();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        await nominationsPage.clickVotingTab();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await votingPage.clickSubmit();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await votingPage.confirmSubmit();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await votingPage.verifySubmitBtnHidden();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        await votingPage.verifyVotingReadOnly();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });
